### ISSUE TITLE
[FEATURE] Customizing GTK Window Borders with CSS for Enhanced Window Decorations

### ISSUE THREAD

**Issue by wesleey** [dracula/gtk#296]
I made a modification to the GTK window decorations by adding borders and customizing their appearance using CSS. The main changes include defining custom properties for the border width, color, and radius, which are applied to various types of windows. Here's a breakdown of the modifications:

```css
/*********************
* Window Decorations *
*********************/
window {
  --wm-border-width: 3px;
  --wm-border-color: #6272a4;
  --wm-border-radius: 12px;
}
window.maximized {
  border: var(--wm-border-width) solid var(--wm-border-color);
  border-radius: var(--wm-border-radius);
}
window:not(.maximized) {
  border: none;
}
window.csd {
  margin: 0px;
  border-radius: var(--wm-border-radius);
  border: var(--wm-border-width) solid var(--wm-border-color);
}
window.csd.popup,
window.csd.dialog.message {
  border-radius: 12px;
  border: 4px solid var(--wm-border-color);
}
window.solid-csd {
  margin: 0;
  padding: 4px;
  border-radius: var(--wm-border-radius);
  border: 4px solid var(--wm-border-color);
}
window.popup,
window.ssd {
  border-radius: 12px;
  border: 4px solid var(--wm-border-color);
}
```
![WhatsApp Image 2024-11-26 at 00 48 44](https://github.com/user-attachments/assets/a1b4cced-7f61-40c1-94ba-b41717d91983)

![image](https://github.com/user-attachments/assets/8c9d10bf-e957-4ba4-a5b9-136622a9ac09)
